// frontend/src/component/Navbar.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const Navbar = () => {
  return (
    <nav className="navbar">
      <div className="navbar-links">
        <li><Link to="/">Phegon</Link></li>
        <li><Link to="/add">Add File</Link></li>
        <li><Link to="/">All Files</Link></li>
      </div>
    </nav>
  );
};

export default Navbar;

// frontend/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterOutlet,RouterLink],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {

}

<nav class="navbar">
    <div class="navbar-links">
        <ul>
            <li><a routerLink="/">Phegon</a></li>
            <li><a routerLink="/add">Add File</a></li>
            <li><a routerLink="/">All Files</a></li>
        </ul>
    </div>
</nav>
